### ISSUE TITLE
About the taxi project

### ISSUE THREAD

**Issue by xinyu-site** [bokae/taxi#18]
It's a great project. I have some confusion when using the code, the code doesn't work properly.
Is there any relevant paper I can read?

**Comment by xjtueryx** [comment]
Reloaded modules: city_model, geometry
configs/0804.json
Running simulation with run_id 0804.json.
Batch time 100.
Number of items 3.
Total time simulated 300.
Starting...
Taxi 94.
        Position 22,22
        Travelling towards request 10.

Traceback (most recent call last):

  File "D:/taxi_py/taxi-master\city_model.py", line 1049, in step_time
    self.pickup_request(t.actual_request_executing)

  File "D:/taxi_py/taxi-master\city_model.py", line 702, in pickup_request
    self.taxis_to_request.remove(r.taxi_id)

KeyError: 39


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\taxi_py\taxi-master\run.py", line 25, in <module>
    s.run_batch(run_id, data_path="results/"+p)

  File "D:/taxi_py/taxi-master\city_model.py", line 956, in run_batch
    self.step_time("")

  File "D:/taxi_py/taxi-master\city_model.py", line 1052, in step_time
    print(r)

  File "D:/taxi_py/taxi-master\city_model.py", line 224, in __str__
    s += ["\tWaiting since ", str(self.timestamp['request']), ".\n"]

AttributeError: 'Request' object has no attribute 'timestamp'

**Comment by bokae** [comment]
This is the paper based on the results of the code: https://www.nature.com/articles/s41598-020-63171-9

The code has been updated several times, older configs might not match the current simulation. I am going to look at the issue now.

**Comment by bokanyie** [comment]
I've corrected some minor bugs, and added a test config file. Please try `python run.py configs/passenger_fairness/test.conf`, that should create results in the `results/passenger_fairness/` directory.
